language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl
    - LISP=ecl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

matrix:
  allow_failures:
    - env: LISP=ecl

script:
  - cl -e '(ql:quickload :cl-tui)
           (load "examples/0smoke.lisp")
           (cl-tui.examples::start)'

